# Generated by Django 5.0.6 on 2024-06-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_userprofile_email_userprofile_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
