# Generated by Django 5.0.6 on 2024-06-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userprofile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='numero',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'T.I'), (2, 'C.C'), (3, 'C.E'), (4, 'C.I')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
