# Generated by Django 5.0.6 on 2024-06-24 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acudiente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento_medicacion', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO'), (3, 'NO SABE')], default=3)),
                ('reacciones_alergicas', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO'), (3, 'NO SABE')], default=3)),
                ('transtorno_tension_arterial', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO'), (3, 'NO SABE')], default=3)),
                ('diabetes', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO'), (3, 'NO SABE')], default=3)),
                ('transtornos_emocionales', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO'), (3, 'NO SABE')], default=3)),
                ('enfermedad_respiratoria', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO'), (3, 'NO SABE')], default=3)),
                ('otros', models.CharField(blank=True, max_length=100)),
                ('protesis_dental', models.CharField(blank=True, max_length=100)),
                ('total', models.CharField(blank=True, max_length=100)),
                ('acrilico', models.CharField(blank=True, max_length=100)),
                ('flexible', models.CharField(blank=True, max_length=100)),
                ('parcial', models.CharField(blank=True, max_length=100)),
                ('retenedores', models.CharField(blank=True, max_length=100)),
                ('panoramica', models.CharField(blank=True, max_length=100)),
                ('periapical', models.CharField(blank=True, max_length=100)),
                ('cepillado_dental', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO')])),
                ('seda_dental', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO')])),
                ('enjuague_bucal', models.PositiveSmallIntegerField(choices=[(1, 'SI'), (2, 'NO')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
