# Generated by Django 5.0.6 on 2024-07-20 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=150)),
                ('cantidad', models.FloatField(blank=True)),
                ('estado', models.PositiveSmallIntegerField(choices=[(1, 'Disponible'), (2, 'Agotado'), (3, 'Por Recibir')])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'T.I'), (2, 'C.C'), (3, 'C.E'), (4, 'C.I')], default=2)),
                ('numero', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('ocupacion', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('acudiente', models.CharField(blank=True, max_length=50, null=True)),
                ('edad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('is_superuser', models.BooleanField(blank=True, default=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('fecha', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('protesis', 'Protesis'), ('ortodoncia', 'Ortodoncia')], default='protesis', max_length=20)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('asistio', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fecha_hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='inicio.fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('fecha_historia', models.DateField(blank=True, null=True)),
                ('tratamiento_medicacion', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3)),
                ('reacciones_alergicas', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3)),
                ('transtorno_tension_arterial', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3)),
                ('diabetes', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3)),
                ('transtornos_emocionales', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3)),
                ('enfermedad_respiratoria', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No'), (3, 'Desinformado')], default=3)),
                ('otros', models.CharField(blank=True, max_length=100)),
                ('protesis_dental', models.CharField(blank=True, max_length=100)),
                ('total', models.CharField(blank=True, max_length=100)),
                ('acrilico', models.CharField(blank=True, max_length=100)),
                ('flexible', models.CharField(blank=True, max_length=100)),
                ('parcial', models.CharField(blank=True, max_length=100)),
                ('retenedores', models.CharField(blank=True, max_length=100)),
                ('panoramica', models.CharField(blank=True, max_length=100)),
                ('periapical', models.CharField(blank=True, max_length=100)),
                ('cepillado_dental', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('seda_dental', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('enjuague_bucal', models.PositiveSmallIntegerField(choices=[(1, 'Si'), (2, 'No')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
