# Generated by Django 5.0.6 on 2024-07-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_cita_google_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('asistida', 'Asistida'), ('cancelada', 'Cancelada'), ('inasistida', 'No Asistió')], default='programada', max_length=20),
        ),
    ]
